# Usar una imagen base de Python
FROM python:3.11-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /run

# Copiar los archivos de tu proyecto a la imagen
COPY requirements.txt .

# Instalar las dependencias
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

# Exponer el puerto en el que Flask estará escuchando (por defecto Flask usa 5000)
EXPOSE 5000


# Usar gunicorn para ejecutar la aplicación en producción
CMD ["gunicorn", "run:app", "-b", "0.0.0.0:5000"]
