# Utiliza una imagen base de Python
FROM python:3.9-slim

# Actualiza los repositorios e instala dependencias para IBM DB2
RUN apt-get update && apt-get install -y \
    libdb2-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Instala las dependencias de Python
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copia los archivos de tu aplicación
COPY . /app

# Establecer directorio de trabajo
WORKDIR /app

# Expón el puerto que Flask usa (5000)
EXPOSE 5000

# Configura la ejecución de la aplicación con gunicorn
CMD ["gunicorn", "app:app", "-b", "0.0.0.0:5000"]
